RDKRIDP-1304 :hwselftest is failing in cmf images in rdk emulator morty branch
Reason for change: To fix the build issue with morty branch of
Yocto and this variable is unused in the code
error: 'defaultStreamerPort' defined but not used [-Werror=unused-const-variable=]
Test Procedure: Now issue should not occur in morty
Risks: None

Change-Id: I3207dfced659f72cad8a529467ee7ba4ec07fe11
Signed-off-by: pnandyala <pavan.nandyala@lnttechservices.com>